### ISSUE TITLE
Additional Generic Agent filters

### ISSUE THREAD

**Issue by dpalic** [znuny/znuny-feature-requests#26]
The generic agent is already very powerful, sadly there are a bunch of filters missing.

e.g. it would be helpful to have the options for

- having one match in TO, CC or BCC 
   to be able to select any mail which was intended for the ticket system independently if direct or indirect addressed
- having one to match also FROM field
   e.g. on conversational matching between clients and agents, it would be great to be able to match the named "TO"-fields and also FROM
   e.g. having communication with a client "apple.com" you could so create a filter to match to any from and to-based e-mail fields to assign an SLA via GA, or to assign a queue, or to assign a prio, or...

I will use this issue to extend more such field requirements

**Comment by rkaldung** [comment]
Hello @dpalic,

Generic Agents are there to process tickets. Your requests mention attributes which belong to articles. Even if articles are part of a ticket, it is fundamental difference. I guess when you talk about "match the named TO and FROM" field you want to match a single article of a ticket. Unfortunately, this is not possible because the used full text search does not allow this.

But, as far as I can see, your use case is already covered with a PostMaster filter.

This issues is closed because it is nearly a duplicate if https://github.com/znuny/znuny-feature-requests/issues/5. Please check the other feature request for being updated.
